[AFCS] Saturation for PI regulator and bug fixes
PugachA/UnmannedAerialVehicle pull request #112
Opened 2020-11-04 17:12 UTC by Li2s

2020-11-04 18:24 UTC, PugachA requested changes

2020-11-04 18:24 UTC, PugachA commented on Libraries/PIReg/PIReg.cpp
> +	}
Так читабильнее
```cpp
if (this->integral > this->integral_lim)
    this->integral = this->integral_lim;

if (this->integral < -this->integral_lim)
    this->integral = -this->integral_lim;
```

2020-11-04 18:24 UTC, PugachA commented on Libraries/PIReg/PIReg.cpp
> +	if (this->output > this->output_lim)
Аналогично

2020-11-04 18:24 UTC, PugachA commented on Libraries/PIReg/PIReg.cpp
> +	this->output_lim = output_lim;
Что-то я не понимаю. А если предел от 0 до 1000 например?
У нас же ШИМ от 980 до 2000

2020-11-04 18:26 UTC, PugachA commented on Plane/Core/Src/main.cpp
> +	double k_int_omega_x = 0.1;
Это конечно пздц, как вообще это работало))))

2020-11-05 21:21 UTC, Li2s commented on Libraries/PIReg/PIReg.cpp
> +	this->output_lim = output_lim;
@PugachA регулятор формирует управляющий сигнал, который добавляется к среднему значению ШИМа. Если ошибка ноль - выход регулятора ноль (при условии отсутствия интеграла). Я как раз поэтому и просил сделать для серв +- 30 градусов, чтобы выходом регулятора уже являлись градусы, и не требовалось потом добавлять константу.

2020-11-06 07:05 UTC, PugachA commented on Libraries/PIReg/PIReg.cpp
> +	this->output_lim = output_lim;
Я считаю это неправильно, потому что это класс нельзя будет использовать для двигателя например. И для всех сущностей где диапазон от 0 до .. Что скажешь?

2020-11-06 07:05 UTC, PugachA commented on Libraries/PIReg/PIReg.cpp
> +	else if (this->integral < -this->integral_lim)
Зачем `else`?

2020-11-06 09:18 UTC, Li2s commented on Libraries/PIReg/PIReg.cpp
> +	else if (this->integral < -this->integral_lim)
@PugachA не могу найти разумное объяснение, но на работе не нравится никому, если один иф после другого без элса, с той же переменной в условии, просят исправить. Так же агрилась на это преподша по инфе с первого курса (забыл как ее зовут)

2020-11-06 09:25 UTC, Li2s commented on Libraries/PIReg/PIReg.cpp
> +	this->output_lim = output_lim;
@PugachA давай представим ситуацию, заданная скорость 10 узлов, текущая ноль. В регуляторе вырабатывается ошибка, накапливается интеграл. Как только текущая скорость становится равна заданной, ошибка становится нулевой, пропорциональная часть обнуляется. Однако интеграл ненулевой, он и поддерживает обороты.
Если сделать отдельные значения на ограничения сверху и снизу, я так понимаю ты так хочешь, для того же двигателя, ты подразумеваешь нижнее ограничение ставить ноль?

2020-11-06 09:29 UTC, PugachA commented on Libraries/PIReg/PIReg.cpp
> +	else if (this->integral < -this->integral_lim)
РЕЗАНОВА. Ладно можешь так оставлять, но эти условия одновременно не могут выполниться,  поэтому считаю что else не нужен

2020-11-06 09:31 UTC, PugachA commented on Libraries/PIReg/PIReg.cpp
> +	this->output_lim = output_lim;
Да. Текущая скорость 10, а заданная 0. Регуль сгенерит сигнал, который ниже минимального принимаего сигнала двигателя и что тогда? Тогда двигатель не сможет отработать этот ШИМ

2020-11-06 09:43 UTC, Li2s commented on Libraries/PIReg/PIReg.cpp
> +	this->output_lim = output_lim;
Как он сгенерит сигнал меньше минимального? В описанной тобой ситуации будет списываться интегральная часть, пока обе не станут нулевыми. Кроме того, в Servo.cpp есть ограничилки на pwm.

2020-11-06 13:32 UTC, PugachA commented on Libraries/PIReg/PIReg.cpp
> +	this->output_lim = output_lim;
В Servo нет ограничений. Короче походу надо созвониться

2020-11-06 17:29 UTC, PugachA commented on Libraries/PIReg/PIReg.cpp
> +	this->output_lim = output_lim;
Договарились убрать ограничение выхода и оставить только ограничение на интеграл

2020-11-07 10:01 UTC, PugachA requested changes

2020-11-07 10:01 UTC, PugachA commented on Libraries/PIReg/PIReg.cpp
> +PIReg::PIReg(double k_int, double k_pr, int dt, double integral_lim, double output_lim)
Зачем `dt` можно же использовать `HAL_GetTicks()`

2020-11-07 10:06 UTC, Li2s commented on Libraries/PIReg/PIReg.cpp
> +PIReg::PIReg(double k_int, double k_pr, int dt, double integral_lim, double output_lim)
1) Чтобы была возможность изменить изменить шаг интегрирования
2) Регулятор вызывается из мэйнового тайм менеджера. Мне кажется, что эти тайминги могут немного не совпадать, dt будет плавать от шага к шагу

2020-11-07 10:44 UTC, Li2s commented on Libraries/PIReg/PIReg.cpp
> +PIReg::PIReg(double k_int, double k_pr, int dt, double integral_lim, double output_lim)
https://github.com/PugachA/UnmannedAerialVehicle/issues/116

2020-11-07 10:47 UTC, Li2s commented on Libraries/PIReg/PIReg.cpp
> +PIReg::PIReg(double k_int, double k_pr, int dt, double integral_lim, double output_lim)
#117

2020-11-07 10:57 UTC, PugachA commented
Правь тогда ограничения и будет апрув

2020-11-07 10:57 UTC, PugachA approved these changes

2020-11-07 10:58 UTC, merged