[Servo] Add servo mapping control
PugachA/UnmannedAerialVehicle pull request #114
Opened 2020-11-05 20:24 UTC by PugachA

Добавлено управление серво в относительных единицах

2020-11-05 21:29 UTC, Li2s commented on Libraries/Servo/Servo.cpp
> +	: Servo(TIM, channel, min_PWM_value, max_PWM_value, 0, 100)
Это значит что по умолчанию будет 0-100?

2020-11-05 21:39 UTC, Li2s commented on Libraries/Servo/Servo.cpp
> +Servo::Servo(TIM_TypeDef *TIM, uint8_t channel, uint32_t min_PWM_value, uint32_t max_PWM_value, double min_input, double max_input)
Предлагаю переназвать min_input и max_input на что-то вроде min_delta_surface и max_delta_surface. Чтобы было понятно что это параметры, а не входы.

2020-11-05 21:50 UTC, Li2s commented on Libraries/Servo/Servo.cpp
> +	uint32_t pwm = this->min_PWM_value + (uint32_t)((position - this->min_input) * this->multiplier);
Вот это вроде правильно, но я не сразу понял. Не удобней будет привести к виду уравнения прямой y=k*x+b? k это по-сути multiplier, мб так же отдельно b посчитать (что-то вроде offset)?

2020-11-05 21:51 UTC, Li2s commented on Logger/Core/Src/main.cpp
> +  Servo ersServo = Servo(htim2.Instance, 1, 530, 2460, 0, 180);
Как насчет задать эти числа говорящими переменными?

2020-11-05 21:52 UTC, Li2s reviewed
Plz take a look at the comments

2020-11-06 07:15 UTC, PugachA commented on Libraries/Servo/Servo.cpp
> +	: Servo(TIM, channel, min_PWM_value, max_PWM_value, 0, 100)
Да

2020-11-06 07:21 UTC, PugachA commented on Libraries/Servo/Servo.cpp
> +Servo::Servo(TIM_TypeDef *TIM, uint8_t channel, uint32_t min_PWM_value, uint32_t max_PWM_value, double min_input, double max_input)
`surface` это типо поверхность самолета? Ну мы же это класс используем для управления двигателем и управления просто сервоприводом. Получается это название не соответствует названиям реального времени. Мне кажется `input` подходит, потому что это фактически и есть максимальное\минимальное входное значение.

2020-11-06 07:26 UTC, PugachA commented on Libraries/Servo/Servo.cpp
> +	uint32_t pwm = this->min_PWM_value + (uint32_t)((position - this->min_input) * this->multiplier);
Ты уверен, что приведение к виду y=k*x+b будет более понятнее? Я считаю понятнее будет писать формулу в полном виде, чтобы понять всю логику, но я решил вынести `multiplier`, чтобы оптимизировать вычисления.
```cpp
(uint32_t)((position - min_input) * (max_PWM_value - min_PWM_value ) / (max_input- min_input) + min_PWM_value )
```

2020-11-06 09:28 UTC, Li2s commented on Libraries/Servo/Servo.cpp
> +	: Servo(TIM, channel, min_PWM_value, max_PWM_value, 0, 100)
Может лучше пусть ошибка будет, если пределы не инициализированы? Сможем отловить такую фигню не в поле (почему у нас поверхности не до конца отклоняются) а на компиляции?

2020-11-06 09:30 UTC, Li2s commented on Libraries/Servo/Servo.cpp
> +Servo::Servo(TIM_TypeDef *TIM, uint8_t channel, uint32_t min_PWM_value, uint32_t max_PWM_value, double min_input, double max_input)
Ну можно просто min_delta max_delta. Вход как-то путает

2020-11-06 09:31 UTC, Li2s commented on Libraries/Servo/Servo.cpp
> +	uint32_t pwm = this->min_PWM_value + (uint32_t)((position - this->min_input) * this->multiplier);
Странно что один кэф вынесен, второй нет. Мне было бы понятнее, но это субъективно. @NoMonsters выскажи третье мнение pls

2020-11-06 09:34 UTC, PugachA commented on Libraries/Servo/Servo.cpp
> +	: Servo(TIM, channel, min_PWM_value, max_PWM_value, 0, 100)
Да можно убрать этот конструктор, но тебя не спасет компиляция, если ты укажешь неверные пределы.

2020-11-06 09:36 UTC, NoMonsters commented on Libraries/Servo/Servo.cpp
> +Servo::Servo(TIM_TypeDef *TIM, uint8_t channel, uint32_t min_PWM_value, uint32_t max_PWM_value, double min_input, double max_input)
Да, согл с Никитой. Лучше чтоб было понятно что это как-то связано с отклонением сервы, а не с сигналом

2020-11-06 09:39 UTC, NoMonsters commented on Logger/Core/Src/main.cpp
> +  Servo ersServo = Servo(htim2.Instance, 1, 530, 2460, 0, 180);
Ну да, где-то обсуждалось, что такие приколы можно вынести в отдельный файл. Правда тогда нужно будет делать extern или что-то такое. Если не юзать define

2020-11-06 09:40 UTC, Li2s commented on Libraries/Servo/Servo.cpp
> +	: Servo(TIM, channel, min_PWM_value, max_PWM_value, 0, 100)
Так хотя бы задумаешься, когда будешь указывать))

2020-11-06 13:31 UTC, NoMonsters requested changes

2020-11-06 13:31 UTC, NoMonsters commented on Logger/Core/Src/main.cpp
> +double ers_close_position = 60; //градусы
почему не const?

2020-11-06 13:31 UTC, NoMonsters commented on Libraries/Servo/Servo.cpp
> +void Servo::setPosition(double position)
Так столько разговоров было в процентах или в градусах. А когда я смотрю на имя функции мне надо больше 2х нейронов активировать, чтобы разобрвать. Мб более говорящее название?

2020-11-06 13:33 UTC, PugachA commented on Libraries/Servo/Servo.cpp
> +void Servo::setPosition(double position)
Ты сам определяешь, что это будет. Это относительные единицы

2020-11-06 13:34 UTC, PugachA commented
Добавить ограничение снизу!

2020-11-06 13:41 UTC, NoMonsters commented on Libraries/Servo/Servo.cpp
> +void Servo::setPosition(double position)
хммм, т.е. когда будешь смотреть код, как понять мы тут в процентах задаем или в градусах сейчас позицию?
Сделай 2 простых метода лучше. А функцию мапинга приватной, например. Кажется так лучше.

2020-11-06 13:48 UTC, PugachA commented on Libraries/Servo/Servo.cpp
> +void Servo::setPosition(double position)
Нет. Когда ты будешь использовать этот он для тебя как черный ящик. Ты сам определяешь на каких диапазонах он работает. В чем принципиальная разница градусов и процентов? Если Никита хочет сначала от -30 до 30 потом захочет от -90 до 90. Я делаю универсальный класс, пользователь сам определяет реальность)

2020-11-06 15:25 UTC, PugachA commented on Libraries/Servo/Servo.cpp
> +Servo::Servo(TIM_TypeDef *TIM, uint8_t channel, uint32_t min_PWM_value, uint32_t max_PWM_value, double min_input, double max_input)
min_mapping_scale

2020-11-06 15:28 UTC, PugachA commented on Libraries/Servo/Servo.cpp
> +Servo::Servo(TIM_TypeDef *TIM, uint8_t channel, uint32_t min_PWM_value, uint32_t max_PWM_value, double min_input, double max_input)
PWMDriver

2020-11-07 10:03 UTC, PugachA commented on Libraries/Servo/Servo.cpp
> +	uint32_t pwm = this->min_PWM_value + (uint32_t)((position - this->min_input) * this->multiplier);
Мне кажется, если сделать два кэфа будет еще труднее определить правильность формулы

2020-11-07 10:59 UTC, Li2s commented on Libraries/Servo/Servo.cpp
> +	uint32_t pwm = this->min_PWM_value + (uint32_t)((position - this->min_input) * this->multiplier);
Не принципиально с моей стороны, но разбираться дольше

2020-11-07 13:05 UTC, Li2s submitted a review, later dismissed

2020-11-07 14:13 UTC, NoMonsters approved these changes

2020-11-07 15:50 UTC, merged