Library for beta sensor added
PugachA/UnmannedAerialVehicle pull request #134
Opened 2020-12-01 13:56 UTC by NoMonsters

2020-12-02 20:51 UTC, Li2s submitted a review, later dismissed

2020-12-02 20:51 UTC, Li2s commented on Libraries/Beta/P3002.cpp
> +	b_adc_to_angle = -2.5;
ну кэфы тут надо будет поправить

2020-12-03 15:52 UTC, PugachA requested changes

2020-12-03 15:52 UTC, PugachA commented on Libraries/Beta/P3002.cpp
> +#include "math.h"
В топку

2020-12-03 15:52 UTC, PugachA commented on Libraries/Beta/P3002.cpp
> +	HAL_ADC_Start(&this->hadc);
Его один раз недостаточно стартануть?

2020-12-03 15:52 UTC, PugachA commented on Libraries/Beta/P3002.cpp
> +	convertADC();
Зачем записывать это в поле класса, если можно просто возвращать в методе `convertADC`? Ты ведб больше нигде это поле не используешь.

2020-12-05 17:12 UTC, NoMonsters commented on Libraries/Beta/P3002.cpp
> +	HAL_ADC_Start(&this->hadc);
недостаточно! Надо каждый раз

2020-12-09 11:33 UTC, NoMonsters commented
Ну шо кто-нибудь править будет? @Li2s

2020-12-09 13:31 UTC, Li2s commented
> Ну шо кто-нибудь править будет? @Li2s 
> 
> 

Поправлю. Дайте отпуск до выходных, пока не уволился с аривала

2021-01-16 10:04 UTC, PugachA approved these changes

2021-01-16 10:04 UTC, PugachA commented on Libraries/Beta/P3002.cpp
> +}
uint32_t adc_raw = convertADC();
double angle = k_adc_to_angle*double(adc_raw) + b_adc_to_angle;

return angle;

2021-01-16 10:16 UTC, merged