[Plane] Vy calc fix
PugachA/UnmannedAerialVehicle pull request #142
Opened 2020-12-06 12:12 UTC by NoMonsters

Стабильно работает вычисление вертикальной скорости
Надо будет подобрать более хорошие кэфы для фильтров

2020-12-06 21:16 UTC, PugachA requested changes

2020-12-06 21:16 UTC, PugachA commented on Libraries/Baro/MS5611.cpp
>      error = k1*(this->filterAltitude - this->first_filter_output);
можно сразу `double error=...`

2020-12-06 21:16 UTC, PugachA commented on Plane/Core/Src/main.cpp
> +	data_input[BAROVY] = ms5611.getVerticalSpeed();
Нужно ли каждый раз перезаписывать занчение? Наверное лучше внести это в if

2020-12-06 21:16 UTC, PugachA commented on Plane/Core/Src/main.cpp
> +			sprintf(str, "%d, %d\n", (int) (100*data_input[BAROVY]), (int) (100*data_input[BARO]));
К сожаления такое не могу пустить в develop, нужно добавить к существующему формату.

2020-12-06 21:17 UTC, PugachA commented
Удалите в это PR еще папку со старым проектом Baro

2020-12-07 07:59 UTC, NoMonsters commented on Plane/Core/Src/main.cpp
> +			sprintf(str, "%d, %d\n", (int) (100*data_input[BAROVY]), (int) (100*data_input[BARO]));
Хорошо, что есть кто это смотрит

2020-12-07 08:00 UTC, NoMonsters commented on Plane/Core/Src/main.cpp
> +	data_input[BAROVY] = ms5611.getVerticalSpeed();
В принципе да, смысла каждый раз писать нет

2020-12-07 08:11 UTC, NoMonsters commented on Libraries/Baro/MS5611.cpp
>      error = k1*(this->filterAltitude - this->first_filter_output);
пофиксил в двух местах, но в коде их ещё много может быть таких

2020-12-07 08:11 UTC, NoMonsters commented on Plane/Core/Src/main.cpp
> +	data_input[BAROVY] = ms5611.getVerticalSpeed();
пофиксил

2020-12-07 08:11 UTC, NoMonsters commented on Plane/Core/Src/main.cpp
> +			sprintf(str, "%d, %d\n", (int) (100*data_input[BAROVY]), (int) (100*data_input[BARO]));
пофиксил

2020-12-07 12:40 UTC, PugachA requested changes

2020-12-07 12:40 UTC, PugachA commented on Plane/Core/Src/main.cpp
> -		#ifdef SERVO_DEBUG_UART
Аналог этого есть для новой реализации?

2020-12-07 12:40 UTC, PugachA commented on Plane/Core/Src/main.cpp
> +					HAL_GetTick(), (int)current_mode ,(int)(0),\
Нафига `\`?

2020-12-07 12:40 UTC, PugachA commented on Plane/Core/Src/main.cpp
> +					HAL_GetTick(), (int)current_mode ,(int)(0),\
Он сейчас всегда 0 `(int)(0)`?

2020-12-07 15:23 UTC, NoMonsters commented on Plane/Core/Src/main.cpp
> +					HAL_GetTick(), (int)current_mode ,(int)(0),\
это перенос строки, неудобно смотреть в одну строку. Пока не 0, но не хочется пока вытаскивать омега_зад из стабилизации, т.к. она там в локальных переменных

2020-12-07 15:23 UTC, NoMonsters commented on Plane/Core/Src/main.cpp
> -		#ifdef SERVO_DEBUG_UART
Нет, я это не юзал и никто не юзал из нас. Видимо нам не нужно, поэтому и убрал

2020-12-07 15:38 UTC, PugachA commented on Plane/Core/Src/main.cpp
> -		#ifdef SERVO_DEBUG_UART
Мы с Никитой при помощи этого поймали багу с некорректным считыванием ШИМ на холоде

2020-12-07 15:39 UTC, PugachA commented on Plane/Core/Src/main.cpp
> +					HAL_GetTick(), (int)current_mode ,(int)(0),\
Разве без `\` нельзя переносить?

2020-12-09 11:26 UTC, NoMonsters commented on Plane/Core/Src/main.cpp
> -		#ifdef SERVO_DEBUG_UART
фигааааа, лан добавил в backlog #143

2020-12-09 11:26 UTC, NoMonsters commented on Plane/Core/Src/main.cpp
> +					HAL_GetTick(), (int)current_mode ,(int)(0),\
Хз, а как ещё? Я такое нагуглил, вроде норм решение, кажется нельзя просто так переносить

2020-12-09 11:27 UTC, NoMonsters commented on Plane/Core/Src/main.cpp
> +					HAL_GetTick(), (int)current_mode ,(int)(0),\
вот надо экранировать http://www.prog.org.ru/topic_18709_0.html

2020-12-09 13:28 UTC, PugachA approved these changes

2020-12-09 14:16 UTC, merged