[ERS] Добавление механизма выталкивания вытяжного парашюта
PugachA/UnmannedAerialVehicle pull request #161
Opened 2021-03-17 19:31 UTC by PugachA

Скорректированы значения для ers серво из-за изменений конструкции
Изменено значение срабатывания ers согласно #159

2021-03-17 19:55 UTC, Li2s approved these changes, later dismissed
Ну вроде понятно

2021-03-17 20:08 UTC, PugachA commented
@Li2s Дай еще раз плиз

2021-03-18 05:43 UTC, NoMonsters approved these changes

2021-03-19 19:05 UTC, NoMonsters requested changes
Изменения т.к. захотели ещё закрылки

2021-03-19 19:05 UTC, NoMonsters commented on Logger/Core/Src/main.cpp
> +const uint16_t ers_pwm = 1900;
Нужно поменять на 2000

2021-03-20 07:21 UTC, NoMonsters commented on Logger/Core/Src/main.cpp
> +const uint16_t ers_pwm = 1900;
@PugachA

2021-03-20 07:30 UTC, NoMonsters approved these changes
уже исправил

2021-03-20 07:31 UTC, merged

2021-03-20 08:34 UTC, PugachA commented
@NoMonsters  Ну ты и перец, сам все правишь, сам апрувишь)