Привыел типы к флоат
PugachA/UnmannedAerialVehicle pull request #174
Opened 2021-04-06 21:03 UTC by NoMonsters

Это исправило проблемы со скачками данных в барометре

2021-04-07 07:29 UTC, PugachA requested changes

2021-04-07 07:29 UTC, PugachA commented on Libraries/Baro/MS5611.cpp
> +  return ((float)(this->pressure))/pres_decimation;
А почему не double?

2021-04-07 18:19 UTC, NoMonsters commented on Libraries/Baro/MS5611.cpp
> +  return ((float)(this->pressure))/pres_decimation;
В даташите на баро флоат указан и переменные которые я юзаю в converRaw тоже привел к флоат
Можно и к дабл наверное, он просто больше и мб медленнее

2021-04-07 18:50 UTC, PugachA commented on Libraries/Baro/MS5611.cpp
> +  return ((float)(this->pressure))/pres_decimation;
Нужно выбрать что-то одно. У тебя метод должен возвращать double, а ты возвращаешь float. Лишнее приведение типов надо убрать

2021-04-10 20:18 UTC, NoMonsters commented
Ну заменил на дабл

2021-04-11 14:22 UTC, Li2s approved these changes

2021-04-13 11:28 UTC, PugachA approved these changes

2021-04-13 18:18 UTC, merged