Hotfix/Altitude Low Pass Filter was added
PugachA/UnmannedAerialVehicle pull request #74
Opened 2020-09-20 08:48 UTC by Li2s

@PugachA помоги плз разрешить конфликты. Все что связано с логгером удалили, чтоб собирался проект. Не собирается так как на основной плате не инициализировано железо.

2020-09-20 09:30 UTC, PugachA requested changes
Верни удаленные либы и плиз назови PR нормально

2020-09-20 09:30 UTC, PugachA commented on Libraries/Logger/Logger.cpp
> -/*
Ты нафига удалил эти файлы в этом коммите https://github.com/PugachA/UnmannedAerialVehicle/pull/74/commits/6b840a252308599fdfc543618220f9d2da644ae2

2020-09-30 11:14 UTC, Li2s commented
@PugachA забрал из девелопа, файлы остались, добавил либы логгера в эксклюды, поправил некоторые переменные

2020-09-30 11:30 UTC, PugachA requested changes

2020-09-30 11:30 UTC, PugachA commented on Libraries/SDFileManager/SDFileManager.h
> -#include "fatfs.h"
Этот файл нужно вернуть

2020-09-30 11:40 UTC, Li2s commented on Libraries/SDFileManager/SDFileManager.h
> -#include "fatfs.h"
А почему его нет в либах в девелопе?

2020-09-30 19:10 UTC, PugachA commented on Libraries/SDFileManager/SDFileManager.h
> -#include "fatfs.h"
Он есть https://github.com/PugachA/UnmannedAerialVehicle/blob/develop/Libraries/SDFileManager/SDFileManager.h.
Видимо это последствия rebase

2020-10-01 06:12 UTC, Li2s commented on Libraries/SDFileManager/SDFileManager.h
> -#include "fatfs.h"
Да, ссылки на него есть. Просто пытаюсь понять, где сам файл fatfs.h должен лежать

2020-10-01 06:14 UTC, Li2s commented on Libraries/SDFileManager/SDFileManager.h
> -#include "fatfs.h"
@PugachA кажется папка FATFS расположена в папке твоего проекта Logger. Может перенести ее в либы?

2020-10-01 06:22 UTC, PugachA commented on Libraries/SDFileManager/SDFileManager.h
> -#include "fatfs.h"
Не забей. Она автогенерируемая. Ее куб сам генерит. Так что оставь там и просто исключи эту либу из билда

2020-10-01 06:34 UTC, Li2s commented on Libraries/SDFileManager/SDFileManager.h
> -#include "fatfs.h"
Либа исключена, файл восстановлен.

2020-10-01 06:39 UTC, PugachA approved these changes

2020-10-01 06:40 UTC, merged