[Integration] Sensors-main board-logger integration
PugachA/UnmannedAerialVehicle pull request #82
Opened 2020-10-05 12:24 UTC by NoMonsters

- Добавил опрос **бародатчика** в основной код, происходит только в арминге
 - Добавил опрос **ПВД** в основной код, происходит только в армингев
 - Добавил функцию колбэка на таймер 6, чтобы по его переполнению вызывать какие-то события. Если кто-то захочет для этого конфигурить ешё события, там есть секции в которые нужно добавлять счетчики флаги и т.д.
 - В арминге даные отправляются в юарт каждые 50 мС
 - Сделал заглушку с вызовом каждые 10 мС для рсчетов вертикальной скорости. Пока она не работает

2020-10-05 12:28 UTC, NoMonsters commented
Флюгер не делал, нужна либа #83

2020-10-05 16:47 UTC, PugachA requested changes

2020-10-05 16:47 UTC, PugachA commented on Plane/Core/Src/main.cpp
> +				HAL_UART_Transmit(&huart2, (uint8_t*)str, sprintf(str, "alt=%d air_speed=%d\n", (int) (altitude * 100), (int) (voltageAirSpeed)), 1000);
Мало данных, где флюгер и вертикальная скорость?

2020-10-05 16:47 UTC, PugachA commented on Plane/Core/Src/main.cpp
> +				HAL_UART_Transmit(&huart2, (uint8_t*)str, sprintf(str, "Hello\n"), 1000);
Что еще за Hello?
Мы точно не с таким кодом летали

2020-10-05 16:47 UTC, PugachA commented on Plane/Core/Src/main.cpp
> +
Для соединения с логгером по одному проводу нужно включить режим трансмитера например здесь
```
HAL_HalfDuplex_EnableTransmitter(&huart2);
```

2020-10-05 16:47 UTC, PugachA commented on Plane/Core/Src/main.cpp
> +				HAL_UART_Transmit(&huart2, (uint8_t*)str, sprintf(str, "alt=%d air_speed=%d\n", (int) (altitude * 100), (int) (voltageAirSpeed)), 1000);
Вот такой был вывод
```
sprintf(logger_str,"alt=%d;Vy=%d;airspeed_adc=%d;airspeed=%d;beta_adc=%d \r\n",(int)(altitude*100),(int)(vertical_speed*100),(int)pitot_adc_raw,(int)(pitot_airspeed*100),(int)beta_adc_raw);
```

2020-10-06 17:04 UTC, NoMonsters commented on Plane/Core/Src/main.cpp
> +				HAL_UART_Transmit(&huart2, (uint8_t*)str, sprintf(str, "alt=%d air_speed=%d\n", (int) (altitude * 100), (int) (voltageAirSpeed)), 1000);
когда будет либа, см коммент выше

2020-10-06 17:05 UTC, NoMonsters commented on Plane/Core/Src/main.cpp
> +				HAL_UART_Transmit(&huart2, (uint8_t*)str, sprintf(str, "Hello\n"), 1000);
Это заглушка для интегратора вертикальной скорости, т.к. он не работает

2020-10-06 17:12 UTC, NoMonsters commented on Plane/Core/Src/main.cpp
> +
Добавил HAL_HalfDuplex_EnableTransmitter(&huart2); в код

2020-10-06 17:29 UTC, PugachA commented on Plane/Core/Src/main.cpp
> +
Где?

2020-10-06 17:29 UTC, PugachA approved these changes

2020-10-06 17:29 UTC, PugachA commented on Plane/Core/Src/main.cpp
> +
Нашел

2020-10-06 18:29 UTC, merged