[ERS] Adding direct engine mode
PugachA/UnmannedAerialVehicle pull request #95
Opened 2020-10-23 07:46 UTC by PugachA

Добавлено прямое управление ШИМ двигателя через плату `ERS` вместо мультиплексора
Разделены таймеры для захвата(`TIM2`) и генерации(`TIM4`) ШИМ

2020-10-23 08:16 UTC, NoMonsters requested changes
Сделай константами короче эти замечания где-то вверху. У нас может быть много такого в будущем, это будет в отдельной файле каком-то мб

2020-10-23 08:16 UTC, NoMonsters commented on Logger/Core/Src/main.cpp
> +		ersServo.Set_Position(165); //открытие капсылы парашюта
На тебя не похоже, что юзаешь магические цифры

2020-10-23 08:16 UTC, NoMonsters commented on Logger/Core/Src/main.cpp
> +		ersServo.Set_Position(60); //закрытие капсылы парашюта
И тут тоже. Сделай константы `ers_open_pulse_width `и  `ers_close_pulse_width`

2020-10-23 11:20 UTC, PugachA commented on Logger/Core/Src/main.cpp
> +		ersServo.Set_Position(165); //открытие капсылы парашюта
Я просто устал. Контроллеры побеждают
Поправлю

2020-10-23 11:21 UTC, PugachA commented on Logger/Core/Src/main.cpp
> +		ersServo.Set_Position(60); //закрытие капсылы парашюта
Поправлю

2020-10-23 13:53 UTC, PugachA commented
Всё жду апрув

2020-10-23 14:28 UTC, PugachA commented
Добавил инструкцию читать всем https://github.com/PugachA/UnmannedAerialVehicle/wiki/%5BERS%5D-%D0%9A%D0%BE%D0%BC%D0%BC%D1%83%D0%BD%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-%D0%BF%D0%BB%D0%B0%D1%82%D0%B0%D0%BC%D0%B8-%D0%BF%D0%BE-UART

2020-10-24 19:09 UTC, Li2s approved these changes
предметно не смотрел

2020-10-24 19:16 UTC, NoMonsters approved these changes

2020-10-24 19:26 UTC, merged